[strings]
; General
100=Tiedoston lataus
101=Haluatko peruuttaa latauksen?
102=%1 (%2 of %3)
103=%1 KB
104=%1 KB of %2 KB (%3%)

; Status information
110=Haetaan tiedoston tietoja...
111=Uudelleenohjataan kohteeseen %1
112=L‰hetet‰‰n pyyntˆ‰...
113=Selvitet‰‰n kohdetta %1
114=Yhdistetty kohteeseen %1
115=Vastaanotetaan...
116=Yhdistet‰‰n kohteeseen %1

; Error messages
120=Virhe muodostettaessa yhteytt‰ internetiin.\n\n%1
121=Virhe avattaessa kohdetta %1.\n\nPalvelin palautti tilakoodin %2.
122=Virhe luettaessa URL-osoitetta.\n\n%1
123=Virhe kirjoitettaessa tiedostoa %1.\n\n%2
124=Virhe avattaessa tiedostoa %1.\n\n%2
125='%1' ei ole kelvollinen URL-osoite.
126=Virhe avattaessa kohdetta %1.\n\n%2
127=Virhe l‰hetett‰ess‰ pyyntˆ‰.\n\n%1
128=Protokollaa ei tueta. Vain HTTP- ja FTP-protokollia tuetaan.
129=Yhteyden muodostaminen kohteeseen %1 ep‰onnistui.\n\n%2
130=Tilakoodin kysely ep‰onnistui.\n\n%1
131=Virhe pyydett‰ess‰ tiedostoa.\n\n%1

; Other
144=Tietoja...
146=Lataa
147=Asennus lataa nyt lis‰tiedostoja tietokoneellesi.

; labels
160=Tiedosto:
161=Nopeus:
162=Tila:
163=Kulunut aika:
164=J‰ljell‰ oleva aika:
165=Nykyinen tiedosto:
166=Kokonaisedistyminen:
167=Peruuta
168=OK
169=K‰ytt‰j‰nimi ja salasana
170=K‰ytt‰j‰nimi:
171=Salasana:
