//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvPurplePen.Livelox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvPurplePen.Livelox.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Livelox_Consent_cancelButton_Text {
            get {
                return ResourceManager.GetString("Livelox_Consent_cancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Livelox_Consent_continueButton_Text {
            get {
                return ResourceManager.GetString("Livelox_Consent_continueButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to proceed, you need to give permission for Purple Pen to interact with your Livelox account.
        ///
        ///When clicking the Continue button below, you will be redirected to Livelox to give such permission. If not already logged in, enter your Livelox account details or create a new Livelox account. After approval, you will be brought back to Purple Pen and the publishing process will continue.
        ///
        ///If you just want to give permission for a single event, uncheck the &quot;Remember my choice on this computer&quot; checkb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Livelox_Consent_informationLabel_Text {
            get {
                return ResourceManager.GetString("Livelox_Consent_informationLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Livelox_Consent_okButton_Text {
            get {
                return ResourceManager.GetString("Livelox_Consent_okButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my choice on this computer.
        /// </summary>
        public static string Livelox_Consent_rememberConsentCheckBox_Text {
            get {
                return ResourceManager.GetString("Livelox_Consent_rememberConsentCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give permission to interact with your Livelox account.
        /// </summary>
        public static string Livelox_Consent_title_Text {
            get {
                return ResourceManager.GetString("Livelox_Consent_title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Livelox_Publish_cancelButton_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_cancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit in Livelox.
        /// </summary>
        public static string Livelox_Publish_editEventLink_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_editEventLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map and courses have previously been published to the following Livelox event.
        /// </summary>
        public static string Livelox_Publish_existingEventGroupBox_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_existingEventGroupBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livelox is a web-based application for analysis of routes from orienteering races. Participants record their routes in real time using a mobile app, or upload them from their GPS watches afterwards. As an organizer of orienteering trainings or competitions, you can publish maps and courses to Livelox to let spectators follow the competitors in real time, and to let participants analyze their route choices post-race..
        /// </summary>
        public static string Livelox_Publish_informationLabel_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_informationLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about Livelox.
        /// </summary>
        public static string Livelox_Publish_learnMoreLink_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_learnMoreLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Livelox_Publish_publishButton_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_publishButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to another event.
        /// </summary>
        public static string Livelox_Publish_publishToOtherEventButton_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_publishToOtherEventButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user from Purple Pen.
        /// </summary>
        public static string Livelox_Publish_removeUserLink_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_removeUserLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution (pixels per meter in the terrain):.
        /// </summary>
        public static string Livelox_Publish_resolutionLabel_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_resolutionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Livelox_Publish_settingsGroupBox_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_settingsGroupBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Livelox.
        /// </summary>
        public static string Livelox_Publish_showEventLink_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_showEventLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show settings.
        /// </summary>
        public static string Livelox_Publish_showSettingsCheckBox_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_showSettingsCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to Livelox.
        /// </summary>
        public static string Livelox_Publish_title_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the event.
        /// </summary>
        public static string Livelox_Publish_updateEventButton_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_updateEventButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livelox user to act as.
        /// </summary>
        public static string Livelox_Publish_userLabel_Text {
            get {
                return ResourceManager.GetString("Livelox_Publish_userLabel_Text", resourceCulture);
            }
        }
    }
}
