//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurplePen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreMiscText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreMiscText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurplePen.CoreMiscText", typeof(CoreMiscText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All controls.
        /// </summary>
        internal static string AllControls {
            get {
                return ResourceManager.GetString("AllControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Variations.
        /// </summary>
        internal static string AllVariations {
            get {
                return ResourceManager.GetString("AllVariations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid leg number for branch &apos;{1}&apos;.
        /// </summary>
        internal static string BadLegNumber {
            get {
                return ResourceManager.GetString("BadLegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read image file &apos;{0}&apos;..
        /// </summary>
        internal static string CannotReadImageFile {
            get {
                return ResourceManager.GetString("CannotReadImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read map for the following reason: &apos;{0}&apos; Using Optimize/Repair and re-saving in OCAD may fix problems..
        /// </summary>
        internal static string CannotReadMap {
            get {
                return ResourceManager.GetString("CannotReadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read map for the following reason: &apos;{0}&apos; Opening and re-saving the map in the latest version of OpenOrienteering Mapper may fix problems..
        /// </summary>
        internal static string CannotReadMapOOM {
            get {
                return ResourceManager.GetString("CannotReadMapOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code must be one, two, or three letters or digits..
        /// </summary>
        internal static string CodeBadLength {
            get {
                return ResourceManager.GetString("CodeBadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code should not begin with zero..
        /// </summary>
        internal static string CodeBeginsWithZero {
            get {
                return ResourceManager.GetString("CodeBeginsWithZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code must not contain a space..
        /// </summary>
        internal static string CodeContainsSpace {
            get {
                return ResourceManager.GetString("CodeContainsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code should not look like another number when upside-down..
        /// </summary>
        internal static string CodeCouldBeUpsideDown {
            get {
                return ResourceManager.GetString("CodeCouldBeUpsideDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control {0}.
        /// </summary>
        internal static string Control_Code {
            get {
                return ResourceManager.GetString("Control_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string Finish_Short {
            get {
                return ResourceManager.GetString("Finish_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map file must be an OCAD file to use GPX files..
        /// </summary>
        internal static string GpxMustBeOcadMap {
            get {
                return ResourceManager.GetString("GpxMustBeOcadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reproject points; either the coordinate system or the real world coordinates in the OCAD map are wrong..
        /// </summary>
        internal static string GpxReprojectFailure {
            get {
                return ResourceManager.GetString("GpxReprojectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg {0} never reaches branch &apos;{1}&apos;: it was assigned to go a different way in a containing fork..
        /// </summary>
        internal static string LegAssignedOuterBranch {
            get {
                return ResourceManager.GetString("LegAssignedOuterBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg {0} should be assigned to one of branches {1}.
        /// </summary>
        internal static string LegNotAssigned {
            get {
                return ResourceManager.GetString("LegNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg {0} is assigned to both branch &apos;{1}&apos; and branch &apos;{2}&apos;.
        /// </summary>
        internal static string LegUsedTwice {
            get {
                return ResourceManager.GetString("LegUsedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory crossing point.
        /// </summary>
        internal static string MandCrossing_Long {
            get {
                return ResourceManager.GetString("MandCrossing_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossing.
        /// </summary>
        internal static string MandCrossing_Medium {
            get {
                return ResourceManager.GetString("MandCrossing_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string MandCrossing_Short {
            get {
                return ResourceManager.GetString("MandCrossing_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map exchange.
        /// </summary>
        internal static string MapExchange_Long {
            get {
                return ResourceManager.GetString("MapExchange_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        internal static string MapExchange_Medium {
            get {
                return ResourceManager.GetString("MapExchange_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX.
        /// </summary>
        internal static string MapExchange_Short {
            get {
                return ResourceManager.GetString("MapExchange_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Start.
        /// </summary>
        internal static string MapIssue_Long {
            get {
                return ResourceManager.GetString("MapIssue_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Start.
        /// </summary>
        internal static string MapIssue_Medium {
            get {
                return ResourceManager.GetString("MapIssue_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS.
        /// </summary>
        internal static string MapIssue_Short {
            get {
                return ResourceManager.GetString("MapIssue_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdfium PDF converter failed to read PDF file successfully.
        /// </summary>
        internal static string PdfConversionFailed {
            get {
                return ResourceManager.GetString("PdfConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PdfConverter.exe not found.
        /// </summary>
        internal static string PdfConverterNotFound {
            get {
                return ResourceManager.GetString("PdfConverterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read result of PDF conversion from file &apos;{0}&apos;.
        /// </summary>
        internal static string PdfResultNotReadable {
            get {
                return ResourceManager.GetString("PdfResultNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Start_Short {
            get {
                return ResourceManager.GetString("Start_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha {0}.
        /// </summary>
        internal static string Version_Alpha {
            get {
                return ResourceManager.GetString("Version_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta {0}.
        /// </summary>
        internal static string Version_Beta {
            get {
                return ResourceManager.GetString("Version_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC {0}.
        /// </summary>
        internal static string Version_RC {
            get {
                return ResourceManager.GetString("Version_RC", resourceCulture);
            }
        }
    }
}
